name: Build and check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 23

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.14

      - name: Run checks
        run: ./gradlew build check shadowJar

      - name: Run samples
        run: |
          vips --version || (sudo apt update && sudo apt install libvips-dev)
          ./run_samples.sh

  macos-sense-check:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 23

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.14

      - name: Run checks
        run: ./gradlew build check shadowJar

      - name: Run samples
        run: |
          vips --version || ((brew install pkgconf || brew link --overwrite pkgconf) && brew install vips)
          ./run_samples.sh

  windows-sense-check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 23

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.14

      - name: Run samples
        shell: pwsh
        run: |
          Invoke-WebRequest "https://github.com/libvips/build-win64-mxe/releases/download/v8.17.0-rc1/vips-dev-w64-web-8.17.0-rc1-static-ffi.zip" -OutFile "vips_w64.zip"
          (Get-FileHash .\vips_w64.zip).Hash -eq "sha256:ffbea9b23d57a60ef85fd0761510949e66116799ad6c2878c17d31780bd93a8a"
          Expand-Archive vips_w64.zip
          $env:Path = "$pwd\vips_w64\vips-dev-8.17;$pwd\vips_w64\vips-dev-8.17\bin;" + $env:Path 
          Write-Output $env:Path
          Get-ChildItem .\vips_w64\vips-dev-8.17
          .\gradlew.bat sample:clean sample:shadowJar
          java -jar sample/build/libs/sample-all.jar

  docker-checks-matrix:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        variant: ["debian-12", "ubuntu-2404", "ubuntu-2404-jemalloc"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 23

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.14

      - name: Run checks
        run: ./run_single_docker_tests.sh ${{ matrix.variant }}

  docker-checks:
    runs-on: ubuntu-24.04
    name: Verify all Docker checks passed
    needs: [docker-checks-matrix]
    steps:
      - run: exit 0