name: Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 24

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.14

      - name: Regenerate docs and check for changes
        run: bash verify_docs_up_to_date.sh

      - name: Run checks
        run: ./gradlew build check shadowJar

      - name: Run samples
        run: |
          vips --version || (sudo apt update && sudo apt install libvips-dev)
          ./run_samples.sh

      - name: Publish to GitHub Packages
        run: ./gradlew core:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}