// Generated by jextract

package app.photofox.vipsffm.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _GParamSpecULong GParamSpecULong
 * }
 */
public class GParamSpecULong extends _GParamSpecULong {

    GParamSpecULong() {
        // Should not be called directly
    }
}

