// Generated by jextract

package app.photofox.vipsffm.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _VipsTargetClass {
 *     VipsConnectionClass parent_class;
 *     gint64 (*write)(VipsTarget *, const void *, size_t);
 *     void (*finish)(VipsTarget *);
 *     gint64 (*read)(VipsTarget *, void *, size_t);
 *     gint64 (*seek)(VipsTarget *, gint64, int);
 *     int (*end)(VipsTarget *);
 * } VipsTargetClass
 * }
 */
public class VipsTargetClass extends _VipsTargetClass {

    VipsTargetClass() {
        // Should not be called directly
    }
}

