// Generated by jextract

package app.photofox.vipsffm.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _VipsTargetCustom {
 *     VipsTarget parent_object;
 * } VipsTargetCustom
 * }
 */
public class VipsTargetCustom extends _VipsTargetCustom {

    VipsTargetCustom() {
        // Should not be called directly
    }
}

