// Generated by jextract

package app.photofox.vipsffm.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _VipsConnectionClass {
 *     VipsObjectClass parent_class;
 * } VipsConnectionClass
 * }
 */
public class VipsConnectionClass extends _VipsConnectionClass {

    VipsConnectionClass() {
        // Should not be called directly
    }
}

