// Generated by jextract

package app.photofox.vipsffm.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _VipsConnection {
 *     VipsObject parent_object;
 *     int descriptor;
 *     int tracked_descriptor;
 *     int close_descriptor;
 *     char *filename;
 * } VipsConnection
 * }
 */
public class VipsConnection extends _VipsConnection {

    VipsConnection() {
        // Should not be called directly
    }
}

