// Generated by jextract

package app.photofox.vipsffm.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _VipsTarget {
 *     VipsConnection parent_object;
 *     gboolean memory;
 *     gboolean ended;
 *     GString *memory_buffer;
 *     VipsBlob *blob;
 *     unsigned char output_buffer[8500];
 *     int write_point;
 *     gint64 position;
 *     gboolean delete_on_close;
 *     char *delete_on_close_filename;
 * } VipsTarget
 * }
 */
public class VipsTarget extends _VipsTarget {

    VipsTarget() {
        // Should not be called directly
    }
}

